// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjFju3GOx04hkzBkiu9idgb76zLKEzCtM',
    appId: '1:753677101111:web:461e664c23f3200b18b7b2',
    messagingSenderId: '753677101111',
    projectId: 'massanger-259b9',
    authDomain: 'massanger-259b9.firebaseapp.com',
    storageBucket: 'massanger-259b9.appspot.com',
    measurementId: 'G-33TZ5HZW36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7XpvIkfz6nsHCvHG14RwSRyUCharrx0',
    appId: '1:753677101111:android:df3a08673e355c3318b7b2',
    messagingSenderId: '753677101111',
    projectId: 'massanger-259b9',
    storageBucket: 'massanger-259b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6z8CVBAdW3Ld-8Trvy9Rk1bDrq1HOjI',
    appId: '1:753677101111:ios:2e1642d1237d8e2d18b7b2',
    messagingSenderId: '753677101111',
    projectId: 'massanger-259b9',
    storageBucket: 'massanger-259b9.appspot.com',
    iosClientId: '753677101111-pb9ugt0aefbup93qam2qqg14omkhbl58.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6z8CVBAdW3Ld-8Trvy9Rk1bDrq1HOjI',
    appId: '1:753677101111:ios:9a6fb1c57d19ed6118b7b2',
    messagingSenderId: '753677101111',
    projectId: 'massanger-259b9',
    storageBucket: 'massanger-259b9.appspot.com',
    iosClientId: '753677101111-oeeuh7r7pkv74evfcbpm4do00foi4f98.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
